UVM_HOME = /eda/synopsys/2020-21/RHELx86/VCS_2020.12/vcs/R-2020.12/etc/uvm-1.2
UVM_VERBOSITY = UVM_MEDIUM
CFLAGS = full64

TESTNAME ?= base_test
SEED ?= $(shell date +%s) # Use current timestamp as default seed
# COV_DIR ?= ./coverage/$(TESTNAME)_$(shell date +%s) 
# PKT_NUM ?= 10000
# KEY_NUM ?= 100

VCS = vcs -sverilog -full64 -timescale=1ns/1ns -kdb \
      +acc +vpi -debug_access+nomemcbk+dmptf -debug_region+cell \
      +define+UVM_OBJECT_MUST_HAVE_CONSTRUCTOR \
      +incdir+$(UVM_HOME)/src $(UVM_HOME)/src/uvm.sv \
      -cm_cond allops+anywidth+event -cm_noconst \
      $(UVM_HOME)/src/dpi/uvm_dpi.cc -CFLAGS -DVCS -debug -debug_all +define+nobanner

SIMV = ./simv +UVM_TESTNAME=$(TESTNAME) \
       +UVM_VERBOSITY=$(UVM_VERBOSITY) \
       +ntb_random_seed=$(SEED) \
       +UVM_TR_RECORD +UVM_LOG_RECORD \
       -cm line+cond+fsm+branch \
       +verbose=1 -l vcs.log \
       +vcd+vcs_dump.vcd

x: comp 
# x: comp run print_seed
comp:
	$(VCS)  +incdir+../sv \
	    	./SW_DUT.sv \
            ./sw_pkg.sv \
            ./clk_rst_cvg_collector.sv \
            ./sw_env.sv \
            ./sw_if.sv \
            ./virtual_seq.sv \
            ./clk/clk_agent.sv \
            ./clk/clk_driver.sv \
            ./clk/clk_monitor.sv \
            ./clk/clk_sqr.sv \
            ./clk/clk_seq.sv \
            ./clk/clk_pkt.sv \
            ./clk/clk_cvg.sv \
            ./rst/rst_agent.sv \
            ./rst/rst_driver.sv \
            ./rst/rst_monitor.sv \
            ./rst/rst_sqr.sv \
            ./rst/rst_seq.sv \
            ./rst/rst_pkt.sv \
            ./rst/rst_cvg.sv \
            ./tests/tb_top.sv \
		./tests/clk_rst_test.sv \
		./tests/base_test.sv

# run:
# 	@$(SIMV) 

# print_seed:
# 	@echo "Seed used for this run: $(SEED)"

clean:
	@-echo "Cleaning"
	@-rm -rf ./coverage csrc DVEfiles inter.vpd simv simv.daidir ucli.key vc_hdrs.h vcs.log .inter.vpd.uvm verdi.log tr_db.log cm.log verdi_config_file urgReport merged_coverage.ucdb coverage_report
